Server -- payload
payload -> Android
payload -> iOS
payload -> Browser (HTMX+HTMT)

payload: |json
  {
    "_links": {
      "self": { "href": "/api/articles/introduction-to-vdp" }
    },
    "_view": {
      "template": "https://example.com/templates/article-detail",
      "slots": {
        "authorCard": {
          "template": "https://example.com/templates/components/author-card"
        }
      }
    },
    "name": "Introduction to VDP",
    "author": "https://example.com/authors/JohnDoe",
    "datePublished": "2024-04-15"
  }
|
